version: "3"
virtualmachines:
- name: pern-o11y
  image: devrel-instruqt-images/devrel-base-um
  machine_type: e2-standard-2
  environment:
    NODE_ENV: development
  allow_external_ingress:
  - http
  - https
  - high-ports
